// ============================================================================
// mainwindow.h - Header File for Main Window and MPV Widget Classes
// ============================================================================
// Header files in C++ declare the "interface" of classes - what methods and
// data members they have - without providing the full implementation.
// This allows other files to use these classes without needing all the details.
//
// The actual implementation (function bodies) is in mainwindow.cpp.
// ============================================================================

// ----------------------------------------------------------------------------
// Include Guards
// ----------------------------------------------------------------------------
// These #ifndef/#define/#endif directives prevent this header from being
// included multiple times in the same compilation unit, which would cause
// "redefinition" errors. This is a standard C++ pattern.
//
// How it works:
//   1. First time this file is included: MAINWINDOW_H is not defined
//   2. We define MAINWINDOW_H and include all the content
//   3. If included again: MAINWINDOW_H is already defined, so we skip everything
// ----------------------------------------------------------------------------
#ifndef MAINWINDOW_H
#define MAINWINDOW_H

// ----------------------------------------------------------------------------
// Qt Framework Includes
// ----------------------------------------------------------------------------
// Qt organizes its classes into modules. We include only what we need.
// Each #include brings in a class definition from the Qt framework.
// ----------------------------------------------------------------------------

#include <QMainWindow>   // Base class for main application windows.
                         // Provides menu bars, toolbars, status bars, etc.

#include <QWidget>       // Base class for ALL visual UI elements in Qt.
                         // Buttons, labels, text boxes - everything inherits from QWidget.

#include <QSlider>       // A slider widget (we use it for volume control).

#include <QFileDialog>   // Provides native file open/save dialogs.
                         // Automatically uses the OS's native file picker.

#include <QCloseEvent>   // Event object for window close events.
                         // Lets us intercept and handle when user closes the window.

#include <QLabel>        // A widget that displays text or images.
                         // We use it for showing filenames and timestamps.

#include <QTimer>        // Provides repetitive and single-shot timers.
                         // We use it to periodically update the playback time display.

#include <QTime>         // A class for working with time values (hours, minutes, seconds).
                         // Used to format playback position as "HH:MM:SS".

#include <QComboBox>     // A dropdown selection widget.
                         // We use it for audio and subtitle track selection.

#include <mpv/client.h>  // The MPV library's C API header.
                         // This gives us access to all MPV functions for video playback.
                         // MPV is a powerful open-source media player/library.

// ----------------------------------------------------------------------------
// Qt Namespace Declaration
// ----------------------------------------------------------------------------
// This is a forward declaration that tells the compiler "there's a class called
// MainWindow inside the Ui namespace". The actual class is auto-generated by
// Qt's UI compiler (uic) from the mainwindow.ui file.
//
// This pattern is called "PIMPL" (Pointer to IMPLementation) - it keeps the
// auto-generated UI code separate from our logic.
// ----------------------------------------------------------------------------
QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

// ============================================================================
// MpvWidget Class Declaration
// ============================================================================
// This class wraps an MPV player instance and provides a clean interface
// for controlling video playback. Each MpvWidget manages one video player.
//
// Inheritance: MpvWidget inherits from QWidget, making it a Qt widget that
// can be placed in layouts, receive events, etc. (Though in our app, the
// widget itself is hidden since videos play in separate MPV windows.)
// ============================================================================
class MpvWidget : public QWidget {
    // The Q_OBJECT macro is REQUIRED for any class that:
    //   - Uses signals and slots (Qt's event communication system)
    //   - Uses Qt's meta-object features (like dynamic property access)
    //
    // It tells Qt's Meta-Object Compiler (moc) to generate extra code for
    // this class. Without it, signals/slots won't work!
    Q_OBJECT

public:
    // ------------------------------------------------------------------------
    // Public Member Variables
    // ------------------------------------------------------------------------
    // Note: In production code, these would typically be private with accessor
    // methods (getters/setters). They're public here for simplicity since the
    // MainWindow needs direct access to update UI elements.
    // ------------------------------------------------------------------------

    mpv_handle *mpv;            // Pointer to the MPV player instance.
                                 // This is MPV's main handle - all MPV API calls use this.
                                 // nullptr means no player is initialized.

    QLabel *statusLabel;         // Pointer to the label showing the current filename.
                                 // We store this so we can update it when files load.

    QLabel *timeLabel;           // Pointer to the label showing playback time.
                                 // Displays "current / duration" format.

    QTimer *pollTimer;           // Timer that fires periodically to update the time display.
                                 // Qt timers emit a signal at set intervals.

    QComboBox *subtitleCombo;    // Dropdown for selecting subtitle tracks.
                                 // Populated when a video with subtitles is loaded.

    QComboBox *audioCombo;       // Dropdown for selecting audio tracks.
                                 // Populated when a video with multiple audio tracks is loaded.

    // ------------------------------------------------------------------------
    // Constructor and Destructor
    // ------------------------------------------------------------------------

    // Constructor: Creates and initializes the MPV player.
    // The "explicit" keyword prevents implicit type conversions - a C++ best practice.
    // The "parent = nullptr" is a default argument - if no parent is specified,
    // the widget has no parent (it's a top-level widget or will be parented later).
    explicit MpvWidget(QWidget *parent = nullptr);

    // Destructor: Cleans up resources when the widget is destroyed.
    // The ~ prefix indicates a destructor in C++.
    // We use this to properly shut down MPV and free resources.
    ~MpvWidget();

    // ------------------------------------------------------------------------
    // Public Methods - Video Control Interface
    // ------------------------------------------------------------------------
    // These methods provide a clean API for controlling the video player.
    // They hide the complexity of MPV's C API behind simple function calls.
    // ------------------------------------------------------------------------

    void loadVideo(QString path);      // Load and start playing a video file.
                                        // QString is Qt's string class - more powerful than std::string.

    void closeVideo();                  // Stop playback and unload the current video.
                                        // Resets the player to its initial state.

    void setVolume(int value);          // Set the audio volume (0-100 scale).

    void togglePause();                 // Toggle between playing and paused states.

    void seek(double seconds);          // Seek forward or backward by the specified seconds.
                                        // Positive = forward, negative = backward.

    void shutdown();                    // Completely shut down the MPV instance.
                                        // Called when closing the application.
                                        // This is critical for clean app termination!

    // ------------------------------------------------------------------------
    // Subtitle Methods
    // ------------------------------------------------------------------------

    void refreshSubtitleTracks();       // Query MPV for available subtitle tracks and
                                        // populate the subtitle dropdown.

    void setSubtitleTrack(int index);   // Switch to the subtitle track at the given
                                        // dropdown index.

    void loadExternalSubtitles(QString path);  // Load a subtitle file from disk
                                               // (e.g., .srt, .ass files).

    // ------------------------------------------------------------------------
    // Audio Methods
    // ------------------------------------------------------------------------

    void refreshAudioTracks();          // Query MPV for available audio tracks and
                                        // populate the audio dropdown.

    void setAudioTrack(int index);      // Switch to the audio track at the given
                                        // dropdown index.

    // ------------------------------------------------------------------------
    // Utility Methods
    // ------------------------------------------------------------------------

    QString formatTime(double time);    // Convert seconds (e.g., 3661.5) to a
                                        // human-readable string (e.g., "01:01:01").

// ------------------------------------------------------------------------
// Public Slots
// ------------------------------------------------------------------------
// Slots are special methods that can be connected to signals. When a signal
// is emitted, all connected slots are called automatically.
//
// This is Qt's implementation of the Observer pattern - it allows loose
// coupling between objects. The timer doesn't need to know about our widget;
// it just emits a signal, and Qt handles the connection.
// ------------------------------------------------------------------------
public slots:
    void onTimerTick();                 // Called every time pollTimer fires.
                                        // Updates the time display with current position.
};

// ============================================================================
// MainWindow Class Declaration
// ============================================================================
// The main application window. Contains two MpvWidgets (for two video players)
// and all the control UI (buttons, sliders, dropdowns).
//
// Inheritance: MainWindow inherits from QMainWindow, which provides standard
// window features like menu bars, toolbars, and status bars (though we don't
// use all of them in this app).
// ============================================================================
class MainWindow : public QMainWindow
{
    Q_OBJECT  // Required for signals/slots - see explanation above.

public:
    // Constructor: Sets up the entire UI.
    // Creates both players, all controls, and wires up all the connections.
    MainWindow(QWidget *parent = nullptr);

    // Destructor: Cleans up resources.
    ~MainWindow();

protected:
    // ------------------------------------------------------------------------
    // Protected Methods - Event Handlers
    // ------------------------------------------------------------------------
    // "protected" means these can be accessed by this class and its subclasses,
    // but not from outside. Event handlers are typically protected.
    //
    // The "override" keyword tells the compiler we're intentionally replacing
    // a method from the parent class (QMainWindow). If we misspell the method
    // name, the compiler will catch it.
    // ------------------------------------------------------------------------

    void closeEvent(QCloseEvent *event) override;
        // Called when the user tries to close the window (clicking X, Alt+F4, etc.).
        // We override this to properly shut down MPV before the window closes.
        // Without this, the app could hang or crash on exit.

private:
    // ------------------------------------------------------------------------
    // Private Member Variables
    // ------------------------------------------------------------------------
    // "private" means only this class can access these members.
    // This is encapsulation - hiding implementation details from the outside.
    // ------------------------------------------------------------------------

    Ui::MainWindow *ui;     // Pointer to the auto-generated UI class.
                            // Created from mainwindow.ui by Qt's UI compiler.
                            // Contains all widgets defined in the Qt Designer.

    MpvWidget *player1;     // The first video player (left side in the UI).
    MpvWidget *player2;     // The second video player (right side in the UI).
};

#endif // MAINWINDOW_H  // End of include guard
